use_frameworks!

target 'FaviconFinder_Example' do
  platform :macos, '10.10'
  pod 'FaviconFinder', :path => '../'

  target 'FaviconFinder_Tests' do
    inherit! :search_paths
    pod 'FaviconFinder', :path => '../'
  end
  
  target 'FaviconFinder_iOS_Example' do
    platform :ios, '14.0'
    pod 'FaviconFinder', :path => '../'
  end
end
