# swiftlint_version: 0.54.0

disabled_rules:
  - inclusive_language
  - non_optional_string_data_conversion
  - identifier_name

nesting:
  type_level:
    warning: 4

function_body_length:
  warning: 100

opt_in_rules:
  - first_where
  - modifier_order
  - sorted_imports

file_length:
  warning: 750

excluded:
  - .build
  - iOSFaviconFinderExample
  - macOSFaviconFinderExample
  - LinuxFaviconFinderExample
