name: "[iOS] Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (iOS)
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Select the preinstalled Xcode 16 on the runner
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16" # or '16.3', '16.2', etc.

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "6.2.0"
          cache-snapshot: "false"

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Install Dependencies
        run: xcodebuild -resolvePackageDependencies -verbose

      - name: Test
        run: xcodebuild test -scheme FaviconFinder -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' -skipPackagePluginValidation
