name: Unit Tests - iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (iOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9.0'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Test
        run: xcodebuild test -scheme FaviconFinder -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' -skipPackagePluginValidation
